const GET_DATA_REQUEST = 'GET_DATA_REQUEST';
const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
const GET_DATA_FALID = 'GET_DATA_FALID';
const RESET_DATA_LISTS = 'RESET_DATA_LISTS';

export { GET_DATA_REQUEST, GET_DATA_SUCCESS, GET_DATA_FALID, RESET_DATA_LISTS };
